export const FETCH_DATA_REQUEST = 'FETCH_DATA_REQUEST'
export const FETCH_DATA_FAILURE = 'FETCH_DATA_FAILURE'
export const FETCH_DATA_SUCCESS = 'FETCH_DATA_SUCCESS'

export const POST_DATA_REQUEST = 'POST_DATA_REQUEST'
export const POST_DATA_FAILURE = 'POST_DATA_FAILURE'
export const POST_DATA_SUCCESS = 'POST_DATA_SUCCESS'

export const UPDATE_LIKES = 'UPDATE_LIKES'
export const UPDATE_UNLIKES = 'UPDATE_UNLIKES'